import { CardInput } from 'src/ecs/configs/card-input';

export const egyptDeck: CardInput[] = [
  // ===== Guardião da Esfinge (3x) =====
  {
    cardBase: {
      id: 'sphinx-guardian-1',
      title: 'Guardião da Esfinge',
      kind: 'TROOP',
    },
    moviment: {
      speed: 0,
      directions: new Set([]),
      rotation: 0,
      mobility: 'SOLID',
    },
    health: 20,
    cardTags: { tags: ['Tanker', 'Pedra'] },
    attack: {
      title: 'Rugido da Esfinge',
      cost: 2,
      pattern: 'FRONT',
      area: 'MEELE',
      affect: 'ENEMY',
      effect: 'PUSH',
      value: 2,
    },
  },
  {
    cardBase: {
      id: 'sphinx-guardian-2',
      title: 'Guardião da Esfinge',
      kind: 'TROOP',
    },
    moviment: {
      speed: 0,
      directions: new Set([]),
      rotation: 0,
      mobility: 'SOLID',
    },
    health: 20,
    cardTags: { tags: ['Tanker', 'Pedra'] },
    attack: {
      title: 'Rugido da Esfinge',
      cost: 2,
      pattern: 'FRONT',
      area: 'MEELE',
      affect: 'ENEMY',
      effect: 'PUSH',
      value: 2,
    },
  },
  {
    cardBase: {
      id: 'sphinx-guardian-3',
      title: 'Guardião da Esfinge',
      kind: 'TROOP',
    },
    moviment: {
      speed: 0,
      directions: new Set([]),
      rotation: 0,
      mobility: 'SOLID',
    },
    health: 20,
    cardTags: { tags: ['Tanker', 'Pedra'] },
    attack: {
      title: 'Rugido da Esfinge',
      cost: 2,
      pattern: 'FRONT',
      area: 'MEELE',
      affect: 'ENEMY',
      effect: 'PUSH',
      value: 2,
    },
  },

  // ===== Arqueiro de Anúbis (3x) =====
  {
    cardBase: {
      id: 'anubis-archer-1',
      title: 'Arqueiro de Anúbis',
      kind: 'TROOP',
    },
    moviment: {
      speed: 2,
      directions: new Set(['N', 'S', 'E', 'W']),
      rotation: 360,
      mobility: 'SOLID',
    },
    health: 8,
    cardTags: { tags: ['Atirador'] },
    attack: {
      title: 'Flecha Sombria',
      cost: 1,
      pattern: 'FRONT',
      area: 'BOW',
      affect: 'ENEMY',
      effect: 'DAMAGE',
      value: 4,
    },
  },
  {
    cardBase: {
      id: 'anubis-archer-2',
      title: 'Arqueiro de Anúbis',
      kind: 'TROOP',
    },
    moviment: {
      speed: 2,
      directions: new Set(['N', 'S', 'E', 'W']),
      rotation: 360,
      mobility: 'SOLID',
    },
    health: 8,
    cardTags: { tags: ['Atirador'] },
    attack: {
      title: 'Flecha Sombria',
      cost: 1,
      pattern: 'FRONT',
      area: 'BOW',
      affect: 'ENEMY',
      effect: 'DAMAGE',
      value: 4,
    },
  },
  {
    cardBase: {
      id: 'anubis-archer-3',
      title: 'Arqueiro de Anúbis',
      kind: 'TROOP',
    },
    moviment: {
      speed: 2,
      directions: new Set(['N', 'S', 'E', 'W']),
      rotation: 360,
      mobility: 'SOLID',
    },
    health: 8,
    cardTags: { tags: ['Atirador'] },
    attack: {
      title: 'Flecha Sombria',
      cost: 1,
      pattern: 'FRONT',
      area: 'BOW',
      affect: 'ENEMY',
      effect: 'DAMAGE',
      value: 4,
    },
  },

  // ===== Escaravelho Sagrado (3x) =====
  {
    cardBase: { id: 'scarab-1', title: 'Escaravelho Sagrado', kind: 'TROOP' },
    moviment: {
      speed: 3,
      directions: new Set(['N', 'S', 'E', 'W', 'NE', 'NW', 'SE', 'SW']),
      rotation: 360,
      mobility: 'GHOST',
    },
    health: 5,
    cardTags: { tags: ['Místico', 'Inseto'] },
    attack: {
      title: 'Luz Reencarnada',
      cost: 1,
      pattern: 'AROUND',
      area: 'AURA',
      affect: 'ALL',
      effect: 'HEAL',
      value: 2,
    },
  },
  {
    cardBase: { id: 'scarab-2', title: 'Escaravelho Sagrado', kind: 'TROOP' },
    moviment: {
      speed: 3,
      directions: new Set(['N', 'S', 'E', 'W', 'NE', 'NW', 'SE', 'SW']),
      rotation: 360,
      mobility: 'GHOST',
    },
    health: 5,
    cardTags: { tags: ['Místico', 'Inseto'] },
    attack: {
      title: 'Luz Reencarnada',
      cost: 1,
      pattern: 'AROUND',
      area: 'AURA',
      affect: 'ALL',
      effect: 'HEAL',
      value: 2,
    },
  },
  {
    cardBase: { id: 'scarab-3', title: 'Escaravelho Sagrado', kind: 'TROOP' },
    moviment: {
      speed: 3,
      directions: new Set(['N', 'S', 'E', 'W', 'NE', 'NW', 'SE', 'SW']),
      rotation: 360,
      mobility: 'GHOST',
    },
    health: 5,
    cardTags: { tags: ['Místico', 'Inseto'] },
    attack: {
      title: 'Luz Reencarnada',
      cost: 1,
      pattern: 'AROUND',
      area: 'AURA',
      affect: 'ALL',
      effect: 'HEAL',
      value: 2,
    },
  },

  // ===== Soldado do Nilo (3x) =====
  {
    cardBase: { id: 'nile-soldier-1', title: 'Soldado do Nilo', kind: 'TROOP' },
    moviment: {
      speed: 1,
      directions: new Set(['N', 'S', 'E', 'W']),
      rotation: 90,
      mobility: 'SOLID',
    },
    health: 12,
    cardTags: { tags: ['Soldado'] },
    attack: {
      title: 'Golpe do Rio',
      cost: 1,
      pattern: 'FRONT',
      area: 'MEELE',
      affect: 'ENEMY',
      effect: 'DAMAGE',
      value: 3,
    },
  },
  {
    cardBase: { id: 'nile-soldier-2', title: 'Soldado do Nilo', kind: 'TROOP' },
    moviment: {
      speed: 1,
      directions: new Set(['N', 'S', 'E', 'W']),
      rotation: 90,
      mobility: 'SOLID',
    },
    health: 12,
    cardTags: { tags: ['Soldado'] },
    attack: {
      title: 'Golpe do Rio',
      cost: 1,
      pattern: 'FRONT',
      area: 'MEELE',
      affect: 'ENEMY',
      effect: 'DAMAGE',
      value: 3,
    },
  },
  {
    cardBase: { id: 'nile-soldier-3', title: 'Soldado do Nilo', kind: 'TROOP' },
    moviment: {
      speed: 1,
      directions: new Set(['N', 'S', 'E', 'W']),
      rotation: 90,
      mobility: 'SOLID',
    },
    health: 12,
    cardTags: { tags: ['Soldado'] },
    attack: {
      title: 'Golpe do Rio',
      cost: 1,
      pattern: 'FRONT',
      area: 'MEELE',
      affect: 'ENEMY',
      effect: 'DAMAGE',
      value: 3,
    },
  },

  // ===== Sacerdotisa de Ísis (2x) =====
  {
    cardBase: {
      id: 'isis-priestess-1',
      title: 'Sacerdotisa de Ísis',
      kind: 'TROOP',
    },
    moviment: {
      speed: 1,
      directions: new Set(['N', 'S', 'E', 'W']),
      rotation: 360,
      mobility: 'SOLID',
    },
    health: 10,
    cardTags: { tags: ['Místico'] },
    attack: {
      title: 'Cura Divina',
      cost: 2,
      pattern: 'FIXED',
      area: 'UNIQUE',
      affect: 'CONRADE',
      effect: 'HEAL',
      value: 6,
    },
  },
  {
    cardBase: {
      id: 'isis-priestess-2',
      title: 'Sacerdotisa de Ísis',
      kind: 'TROOP',
    },
    moviment: {
      speed: 1,
      directions: new Set(['N', 'S', 'E', 'W']),
      rotation: 360,
      mobility: 'SOLID',
    },
    health: 10,
    cardTags: { tags: ['Místico'] },
    attack: {
      title: 'Cura Divina',
      cost: 2,
      pattern: 'FIXED',
      area: 'UNIQUE',
      affect: 'CONRADE',
      effect: 'HEAL',
      value: 6,
    },
  },

  // ===== Múmia Conjuradora (2x) =====
  {
    cardBase: { id: 'mummy-1', title: 'Múmia Conjuradora', kind: 'TROOP' },
    moviment: {
      speed: 0,
      directions: new Set([]),
      rotation: 0,
      mobility: 'SOLID',
    },
    health: 15,
    cardTags: { tags: ['Morto-Vivo'] },
    attack: {
      title: 'Areia Amaldiçoada',
      cost: 2,
      pattern: 'AROUND',
      area: 'CROSS',
      affect: 'ENEMY',
      effect: 'DAMAGE',
      value: 3,
    },
  },
  {
    cardBase: { id: 'mummy-2', title: 'Múmia Conjuradora', kind: 'TROOP' },
    moviment: {
      speed: 0,
      directions: new Set([]),
      rotation: 0,
      mobility: 'SOLID',
    },
    health: 15,
    cardTags: { tags: ['Morto-Vivo'] },
    attack: {
      title: 'Areia Amaldiçoada',
      cost: 2,
      pattern: 'AROUND',
      area: 'CROSS',
      affect: 'ENEMY',
      effect: 'DAMAGE',
      value: 3,
    },
  },

  // ===== Lanceiro da Necrópole (2x) =====
  {
    cardBase: {
      id: 'necropolis-lancer-1',
      title: 'Lanceiro da Necrópole',
      kind: 'TROOP',
    },
    moviment: {
      speed: 1,
      directions: new Set(['N', 'S']),
      rotation: 90,
      mobility: 'SOLID',
    },
    health: 14,
    cardTags: { tags: ['Soldado'] },
    attack: {
      title: 'Investida Fúnebre',
      cost: 1,
      pattern: 'FRONT',
      area: 'PIERCE',
      affect: 'ENEMY',
      effect: 'DAMAGE',
      value: 5,
    },
  },
  {
    cardBase: {
      id: 'necropolis-lancer-2',
      title: 'Lanceiro da Necrópole',
      kind: 'TROOP',
    },
    moviment: {
      speed: 1,
      directions: new Set(['N', 'S']),
      rotation: 90,
      mobility: 'SOLID',
    },
    health: 14,
    cardTags: { tags: ['Soldado'] },
    attack: {
      title: 'Investida Fúnebre',
      cost: 1,
      pattern: 'FRONT',
      area: 'PIERCE',
      affect: 'ENEMY',
      effect: 'DAMAGE',
      value: 5,
    },
  },

  // ===== Falcão de Hórus (2x) =====
  {
    cardBase: { id: 'horus-hawk-1', title: 'Falcão de Hórus', kind: 'TROOP' },
    moviment: {
      speed: 3,
      directions: new Set(['N', 'S', 'E', 'W', 'NE', 'NW', 'SE', 'SW']),
      rotation: 720,
      mobility: 'JUMPER',
    },
    health: 6,
    cardTags: { tags: ['Voador'] },
    attack: {
      title: 'Rasante Solar',
      cost: 1,
      pattern: 'FRONT',
      area: 'DELTA',
      affect: 'ENEMY',
      effect: 'DAMAGE',
      value: 3,
    },
  },
  {
    cardBase: { id: 'horus-hawk-2', title: 'Falcão de Hórus', kind: 'TROOP' },
    moviment: {
      speed: 3,
      directions: new Set(['N', 'S', 'E', 'W', 'NE', 'NW', 'SE', 'SW']),
      rotation: 720,
      mobility: 'JUMPER',
    },
    health: 6,
    cardTags: { tags: ['Voador'] },
    attack: {
      title: 'Rasante Solar',
      cost: 1,
      pattern: 'FRONT',
      area: 'DELTA',
      affect: 'ENEMY',
      effect: 'DAMAGE',
      value: 3,
    },
  },

  // ===== Escorpião do Deserto (2x) =====
  {
    cardBase: {
      id: 'desert-scorpion-1',
      title: 'Escorpião do Deserto',
      kind: 'TROOP',
    },
    moviment: {
      speed: 2,
      directions: new Set(['N', 'S', 'E', 'W']),
      rotation: 180,
      mobility: 'SOLID',
    },
    health: 7,
    cardTags: { tags: ['Animal'] },
    attack: {
      title: 'Ferroada Venenosa',
      cost: 1,
      pattern: 'FRONT',
      area: 'MEELE',
      affect: 'ENEMY',
      effect: 'DAMAGE',
      value: 4,
    },
  },
  {
    cardBase: {
      id: 'desert-scorpion-2',
      title: 'Escorpião do Deserto',
      kind: 'TROOP',
    },
    moviment: {
      speed: 2,
      directions: new Set(['N', 'S', 'E', 'W']),
      rotation: 180,
      mobility: 'SOLID',
    },
    health: 7,
    cardTags: { tags: ['Animal'] },
    attack: {
      title: 'Ferroada Venenosa',
      cost: 1,
      pattern: 'FRONT',
      area: 'MEELE',
      affect: 'ENEMY',
      effect: 'DAMAGE',
      value: 4,
    },
  },

  // ===== Colosso de Pedra (2x) =====
  {
    cardBase: {
      id: 'stone-colossus-1',
      title: 'Colosso de Pedra',
      kind: 'TROOP',
    },
    moviment: {
      speed: 0,
      directions: new Set([]),
      rotation: 0,
      mobility: 'SOLID',
    },
    health: 22,
    cardTags: { tags: ['Tanker', 'Pedra'] },
    attack: {
      title: 'Pisada Sísmica',
      cost: 2,
      pattern: 'AROUND',
      area: 'CROSS',
      affect: 'ENEMY',
      effect: 'DAMAGE',
      value: 4,
    },
  },
  {
    cardBase: {
      id: 'stone-colossus-2',
      title: 'Colosso de Pedra',
      kind: 'TROOP',
    },
    moviment: {
      speed: 0,
      directions: new Set([]),
      rotation: 0,
      mobility: 'SOLID',
    },
    health: 22,
    cardTags: { tags: ['Tanker', 'Pedra'] },
    attack: {
      title: 'Pisada Sísmica',
      cost: 2,
      pattern: 'AROUND',
      area: 'CROSS',
      affect: 'ENEMY',
      effect: 'DAMAGE',
      value: 4,
    },
  },

  // ===== Cobra de Sobek (2x) =====
  {
    cardBase: { id: 'sobek-serpent-1', title: 'Cobra de Sobek', kind: 'TROOP' },
    moviment: {
      speed: 2,
      directions: new Set(['N', 'S', 'E', 'W']),
      rotation: 180,
      mobility: 'SOLID',
    },
    health: 9,
    cardTags: { tags: ['Animal'] },
    attack: {
      title: 'Mordida do Pântano',
      cost: 1,
      pattern: 'FRONT',
      area: 'MEELE',
      affect: 'ENEMY',
      effect: 'DAMAGE',
      value: 4,
    },
  },
  {
    cardBase: { id: 'sobek-serpent-2', title: 'Cobra de Sobek', kind: 'TROOP' },
    moviment: {
      speed: 2,
      directions: new Set(['N', 'S', 'E', 'W']),
      rotation: 180,
      mobility: 'SOLID',
    },
    health: 9,
    cardTags: { tags: ['Animal'] },
    attack: {
      title: 'Mordida do Pântano',
      cost: 1,
      pattern: 'FRONT',
      area: 'MEELE',
      affect: 'ENEMY',
      effect: 'DAMAGE',
      value: 4,
    },
  },

  // ===== Trunfos — 3 cartas únicas =====
  {
    cardBase: { id: 'eye-of-ra', title: 'Olho de Rá', kind: 'TRUMP' },
    attack: {
      title: 'Raio Solar',
      cost: 0,
      pattern: 'FIXED',
      area: 'ROW',
      affect: 'ENEMY',
      effect: 'DAMAGE',
      value: 6,
    },
  },
  {
    cardBase: { id: 'sandstorm', title: 'Tempestade de Areia', kind: 'TRUMP' },
    attack: {
      title: 'Areia Cortante',
      cost: 0,
      pattern: 'AROUND',
      area: 'X',
      affect: 'ALL',
      effect: 'PUSH',
      value: 1,
    },
  },
  {
    cardBase: { id: 'isis-blessing', title: 'Bênção de Ísis', kind: 'TRUMP' },
    attack: {
      title: 'Luz Restauradora',
      cost: 0,
      pattern: 'FIXED',
      area: 'COLUMN',
      affect: 'CONRADE',
      effect: 'HEAL',
      value: 8,
    },
  },
];
